package com.govindan.poc.retailstore.domain.model;

// default package
// Generated 25-Feb-2023, 3:37:30 pm by Hibernate Tools 6.1.3.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * CountryStore generated by hbm2java
 */
@Entity
@Table(name = "country_store", schema = "public")
@JsonIgnoreProperties({"hibernateLazyInitializer","countryStoreProducts"})
public class CountryStore implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String id;
	private Country country;
	private Store store;
	private Set<CountryStoreProduct> countryStoreProducts = new HashSet<>();

	public CountryStore() {
	}

	public CountryStore(String id) {
		this.id = id;
	}

	public CountryStore(String id, Country country, Store store, Set<CountryStoreProduct> countryStoreProducts) {
		this.id = id;
		this.country = country;
		this.store = store;
		this.countryStoreProducts = countryStoreProducts;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 8)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "country_id")
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_id")
	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countryStore")
	@JsonIgnore
	public Set<CountryStoreProduct> getCountryStoreProducts() {
		return this.countryStoreProducts;
	}

	public void setCountryStoreProducts(Set<CountryStoreProduct> countryStoreProducts) {
		this.countryStoreProducts = countryStoreProducts;
	}

}
