package com.govindan.poc.retailstore.domain.model;

// default package
// Generated 25-Feb-2023, 3:37:30 pm by Hibernate Tools 6.1.3.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "country", schema = "public")
@JsonIgnoreProperties({"hibernateLazyInitializer","countryStores"})
public class Country implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String id;
	private String name;
	private String currencyCode;
	private Set<CountryStore> countryStores = new HashSet<>();

	public Country() {
	}

	public Country(String id) {
		this.id = id;
	}

	public Country(String id, String name, String currencyCode, Set<CountryStore> countryStores) {
		this.id = id;
		this.name = name;
		this.currencyCode = currencyCode;
		this.countryStores = countryStores;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 2)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "currency_code", length = 3)
	public String getCurrencyCode() {
		return this.currencyCode;
	}

	public void setCurrencyCode(String currencyCode) {
		this.currencyCode = currencyCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
	@JsonIgnore
	public Set<CountryStore> getCountryStores() {
		return this.countryStores;
	}

	public void setCountryStores(Set<CountryStore> countryStores) {
		this.countryStores = countryStores;
	}

}
