package com.govindan.poc.retailstore.domain.model;

import java.math.BigDecimal;
import java.sql.Timestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

// default package
// Generated 25-Feb-2023, 3:37:30 pm by Hibernate Tools 6.1.3.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * CountryStoreProduct generated by hbm2java
 */
@Entity
@Table(name = "country_store_product", schema = "public")
@JsonIgnoreProperties({"hibernateLazyInitializer"})
public class CountryStoreProduct implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String id;
	private CountryStore countryStore;
	private Product product;
	private String sku;
	private BigDecimal price;
	private Timestamp lastFeedDate;

	public CountryStoreProduct() {
	}

	public CountryStoreProduct(String id) {
		this.id = id;
	}

	public CountryStoreProduct(String id, CountryStore countryStore, Product product, String sku, BigDecimal price,
			Timestamp lastFeedDate) {
		this.id = id;
		this.countryStore = countryStore;
		this.product = product;
		this.sku = sku;
		this.price = price;
		this.lastFeedDate = lastFeedDate;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 263)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "country_store_id")
	public CountryStore getCountryStore() {
		return this.countryStore;
	}

	public void setCountryStore(CountryStore countryStore) {
		this.countryStore = countryStore;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_name")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "sku")
	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

	@Column(name = "price", precision = 0, scale = 0)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_feed_date", length = 35)
	public Timestamp getLastFeedDate() {
		return this.lastFeedDate;
	}

	public void setLastFeedDate(Timestamp lastFeedDate) {
		this.lastFeedDate = lastFeedDate;
	}

}
