package com.govindan.poc.retailstore.domain.model;

// default package
// Generated 25-Feb-2023, 3:37:30 pm by Hibernate Tools 6.1.3.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", schema = "public")
@JsonIgnoreProperties({"hibernateLazyInitializer","countryStoreProducts"})
public class Product implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String name;
	private String description;
	private Set<CountryStoreProduct>  countryStoreProducts= new HashSet<>();

	public Product() {
	}

	public Product(String name) {
		this.name = name;
	}

	public Product(String name, String description, Set<CountryStoreProduct> countryStoreProducts) {
		this.name = name;
		this.description = description;
		this.countryStoreProducts = countryStoreProducts;
	}

	@Id

	@Column(name = "name", unique = true, nullable = false, length = 255)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	@JsonIgnore
	public Set<CountryStoreProduct> getCountryStoreProducts() {
		return this.countryStoreProducts;
	}

	public void setCountryStoreProducts(Set<CountryStoreProduct> countryStoreProducts) {
		this.countryStoreProducts = countryStoreProducts;
	}

}
