package com.govindan.poc.retailstore.domain.model;

// default package
// Generated 25-Feb-2023, 3:37:30 pm by Hibernate Tools 6.1.3.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Store generated by hbm2java
 */
@Entity
@Table(name = "store", schema = "public")
@JsonIgnoreProperties({"hibernateLazyInitializer","countryStores"})
public class Store implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String id;
	private String name;
	private Set<CountryStore> countryStores = new HashSet<>();

	public Store() {
	}

	public Store(String id) {
		this.id = id;
	}

	public Store(String id, String name, Set<CountryStore> countryStores) {
		this.id = id;
		this.name = name;
		this.countryStores = countryStores;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 6)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "store")
	public Set<CountryStore> getCountryStores() {
		return this.countryStores;
	}

	public void setCountryStores(Set<CountryStore> countryStores) {
		this.countryStores = countryStores;
	}

}
